minWorkers: 1
maxWorkers: 1
responseTimeout: 1500

handler:
    model_name: ""
    batch_size: 1
    max_length: 1024 
    max_new_tokens: 128
    ipex_weight_only_quantization: true
    woq_dtype: "INT8"
    lowp_mode: "BF16"
    act_quant_mode: "PER_IC_BLOCK"
    group_size: -1
    token_latency: true
    benchmark: true 
    num_warmup: 2
    num_iter: 8
    greedy: true
    
